name: paystack-go-sdk

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
    
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      -
        name: Build
        run: go build -v ./...
      
      - 
        name: Test
        run: go test -v ./...
